---
# Manage all common applications on AWS AMI-LINUX-2 servers is RHEL 6.x

# On AWS AMI Linux 2 you have to install php72 the AWS way
- name: Ensure AWS Linux 2 installs maraidb-10.2
  command: amazon-linux-extras install -y lamp-mariadb10.2-php7.


#- name: Ensure php-fpm socket directory exists
#  file:
#      name: /run/php-fpm
#      state: directory

- name: Ensure maraidb-server 10.2 
  yum:
      name: mariadb-server 
      state: present

#  notify: systemctl-mariadb-service
#  tags: mariadb102

#- name: Configure MariaDB
#  template:
#     src: 
#     destination: /etc/mysql.d/m

# secure
