# Manage all common applications on CENTOS servers
#
---
- name: Ensure system timezone is "{{ date_timezone }}" 
  timezone:
      name: "{{ date_timezone }}"

- name: Ensure essential tools
  yum:
      name: "{{ item.name }}"
      state: latest
  with_items:
      - "{{ common_app_list }}"

# Copy files from tmpl to destination
- name: Ensure vimrc
  copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      owner: "{{ item.owner }}"
      mode:  0640
  with_items:
    - "{{ vimrc }}"
    
- name: Ensure user home vim path
  file:
      name: "{{ item.name }}"
      owner: "{{ item.owner }}"
      mode: 0750
      state: directory
  with_items:
    - "{{ user_dirs }}"

# System Utilities update
- name: Yum userland update
  yum:
      name: '*'
      exclude: kernel*
      state: latest

# System Kernel update
- name: Yum kernel update
  yum:
      name: kernel*
      state: latest 
  register: kernel_update
 
- name: Reboot if kernel is updated
  command: /sbin/shutdown -r +2
  async: 0
  poll: 0
  ignore_errors: true
  when: kernel_update.changed
  
- name: Wait for machine to be alive
  wait_for_connection:
      timeout: 360
